import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const source = readFileSync(new URL('./perimeter-controls.ts', import.meta.url), 'utf8')
const selectSource = readFileSync(new URL('../components/ui/select.tsx', import.meta.url), 'utf8')
const globalsSource = readFileSync(new URL('../app/globals.css', import.meta.url), 'utf8')
const colorChipsSource = readFileSync(new URL('../components/gradient/canvas-color-chips.tsx', import.meta.url), 'utf8')
const sizeControlsSource = readFileSync(new URL('../components/gradient/canvas-size-controls.tsx', import.meta.url), 'utf8')
const actionsSource = readFileSync(new URL('../components/gradient/canvas-actions.tsx', import.meta.url), 'utf8')
const experimentToolbarSource = readFileSync(new URL('../components/gradient/experiment-toolbar.tsx', import.meta.url), 'utf8')
const perimeterControlsSource = readFileSync(new URL('../components/gradient/perimeter-controls.tsx', import.meta.url), 'utf8')
const canvasStageSource = readFileSync(new URL('../components/gradient/canvas-stage.tsx', import.meta.url), 'utf8')

test('canvas perimeter bars share a fixed 36px height', () => {
  assert.match(source, /export const CONTROL_HEIGHT = 36/)
  assert.match(source, /CONTROL_HEIGHT_CLASS = 'h-9 min-h-9'/)
  assert.match(source, /CONTROL_SURFACE_CLASS = `\$\{CONTROL_HEIGHT_CLASS\}/)
  assert.match(colorChipsSource, /CONTROL_SURFACE_CLASS/)
  assert.match(sizeControlsSource, /CONTROL_INTERACTIVE_SURFACE_CLASS/)
  assert.match(actionsSource, /CONTROL_SURFACE_CLASS/)
  assert.match(experimentToolbarSource, /CONTROL_SURFACE_CLASS/)
  assert.doesNotMatch(experimentToolbarSource, /rounded-\[14px\][^"']*p-1\.5/)
})

test('mask and steps share the generate toolbar row with the standard gap', () => {
  assert.match(experimentToolbarSource, /aria-label="마스크 효과"/)
  assert.match(experimentToolbarSource, /aria-label="단계"/)
  assert.match(experimentToolbarSource, /w-\[236px\]/)
  assert.match(experimentToolbarSource, /h-\[48px\]/)
  assert.match(experimentToolbarSource, /viewBox="0 0 236 48"/)
  assert.match(experimentToolbarSource, /function StepsCornerSlider/)
  assert.match(experimentToolbarSource, /STEP_TRACK_CURVE_END/)
  assert.match(experimentToolbarSource, /STEP_SURFACE_PATH/)
  assert.match(experimentToolbarSource, /STEP_TRACK_CURVE_START = \{ x: 154, y: 18 \}/)
  assert.match(experimentToolbarSource, /STEP_TRACK_ARC_RADIUS = 104/)
  assert.match(experimentToolbarSource, /role="slider"/)
  assert.match(experimentToolbarSource, /A \$\{STEP_TRACK_ARC_RADIUS\} \$\{STEP_TRACK_ARC_RADIUS\}/)
  assert.match(experimentToolbarSource, /M 12 0 H 154 A 112 112 0 0 1 222 26/)
  assert.doesNotMatch(experimentToolbarSource, /viewBox="0 0 222 36"/)
  assert.doesNotMatch(experimentToolbarSource, /viewBox="0 0 222 48"/)
  assert.doesNotMatch(experimentToolbarSource, /STEP_TRACK_CONTROL_1/)
  assert.doesNotMatch(experimentToolbarSource, /STEP_TRACK_CONTROL_2/)
  assert.doesNotMatch(experimentToolbarSource, /222 40/)
  assert.doesNotMatch(experimentToolbarSource, /<Slider/)
  assert.doesNotMatch(experimentToolbarSource, /style=\{\{ width: 168 \}\}/)
  assert.doesNotMatch(perimeterControlsSource, /label="단계"/)
  assert.doesNotMatch(perimeterControlsSource, /aria-label="마스크 효과"/)
})

test('color panel swatches update before the outside pointerdown closer can unmount them', () => {
  assert.match(colorChipsSource, /onPointerDownCapture=\{selectQuickColorFromEvent\}/)
  assert.match(colorChipsSource, /onMouseDownCapture=\{selectQuickColorFromEvent\}/)
  assert.match(colorChipsSource, /event\.stopPropagation\(\)/)
  assert.match(colorChipsSource, /data-swatch=\{swatch\}/)
  assert.match(colorChipsSource, /updateColor\(activeColorIndex, swatch\)/)
  assert.match(colorChipsSource, /window\.setTimeout\(close, 0\)/)
  assert.match(colorChipsSource, /key=\{`palette-color-\$\{index\}`\}/)
  assert.doesNotMatch(colorChipsSource, /key=\{`\$\{color\}-\$\{index\}`\}/)
})

test('floating color and export panels render above canvas point handles', () => {
  assert.match(canvasStageSource, /function PointHandles/)
  assert.match(canvasStageSource, /className="absolute h-6 w-6/)
  assert.match(canvasStageSource, /absolute left-0 top-full z-\[80\]/)
  assert.match(canvasStageSource, /absolute inset-0 z-\[30\]/)
  assert.match(colorChipsSource, /z-\[90\]/)
  assert.match(actionsSource, /z-\[90\]/)
  assert.match(actionsSource, /rootRef\.current\?\.contains\(target\)/)
  assert.match(actionsSource, /document\.addEventListener\('pointerdown', closeIfOutside, true\)/)
  assert.match(actionsSource, /document\.addEventListener\('keydown', closeOnEscape, true\)/)
})

test('select popovers close from document-level outside interactions', () => {
  assert.match(selectSource, /document\.addEventListener\('pointerdown', closeIfOutside, true\)/)
  assert.match(selectSource, /document\.addEventListener\('click', closeIfOutside, true\)/)
  assert.match(selectSource, /document\.addEventListener\('keydown', closeOnEscape, true\)/)
  assert.match(selectSource, /triggerRef\.current\?\.contains\(target\)/)
  assert.match(selectSource, /contentRef\.current\?\.contains\(target\)/)
})

test('select popovers reveal subtle scrollbars for overflowing menus', () => {
  assert.match(selectSource, /pg-select-content/)
  assert.match(selectSource, /pg-select-viewport max-h-\[inherit\] overflow-y-auto/)
  assert.match(globalsSource, /\.pg-select-viewport/)
  assert.match(globalsSource, /scrollbar-color: rgba\(255,255,255,0\.24\) transparent/)
  assert.match(globalsSource, /\.pg-select-content:hover \.pg-select-viewport/)
  assert.match(globalsSource, /scrollbar-color: rgba\(255,255,255,0\.54\) transparent/)
  assert.match(globalsSource, /\.pg-select-viewport::-webkit-scrollbar-thumb:hover/)
})
